version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    user: root
    volumes:
      - ./jenkins_data/:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home  
    ports:
      - "8080:8080"


